### ISSUE TITLE
Derivative

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaMath/MittagLeffler.jl#1] opened 2018-01-22 16:21 UTC
I have extended this slightly to incorporate the derivative, using the method from the reference paper. Tested it and it works OK apart from there seems to be a bug I can't find yet which means it is out by *-1 factor compared with the numerical derivative. Let me know if you have any interest in adding this to your module and I'll try and fix and create pull request.

**Comment by jlapeyre** [comment] 2018-01-25 18:25
Hi, Yes, that would be great. Thanks for the contribution!

**Comment by jlapeyre** [comment] 2018-01-31 21:15
I don't know why you don't show up as a 'contributor'.  Maybe the way I merged the request ?

**Comment by moustachio-belvedere** [comment] 2018-02-01 16:36
Hmm I'm not sure. Just had a read of https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/ but I'm not sure if any of the 'not included' criteria apply.

**Comment by jlapeyre** [comment] 2018-02-01 20:01
Well, I'll look at it a little. If you find what the problem is, I'll gladly try to rectify it.

**Comment by moustachio-belvedere** [comment] 2018-02-05 16:43
Thanks, I'll make sure to let you know when the rheology software is up.

**Comment by moustachio-belvedere** [comment] 2018-02-23 13:23
Still can't figure out why I'm not shown as contributor, oh well doesn't matter :)

**Closed as completed** 2018-02-23 13:23 UTC

**Comment by jlapeyre** [comment] 2018-02-23 13:26
Well maybe it does. If you have a lot of other contributions, maybe not.
Anyway I am super busy now.  Thanks again for the contribution!

**Comment by moustachio-belvedere** [comment] 2018-02-23 17:06
No problem. I think I figured it out, my local git credentials are slightly different as I also use a bitbucket account, so although I pushed it to this github account it thinks its from someone else.
